# Generated by Django 3.2.5 on 2021-10-28 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('OwnerId', models.AutoField(primary_key=True, serialize=False)),
                ('OwnerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('TestId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('PackageId', models.AutoField(primary_key=True, serialize=False)),
                ('PackageName', models.CharField(max_length=50)),
                ('PackageDescription', models.TextField()),
                ('PackageVersion', models.CharField(max_length=50)),
                ('PackagePath', models.CharField(max_length=200)),
                ('LatestUpdate', models.DateField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.group')),
            ],
        ),
    ]
