# Generated by Django 3.2.5 on 2021-11-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PackageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(blank=True, null=True)),
                ('URL', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageMetadata',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusFactor', models.DecimalField(decimal_places=9, max_digits=10)),
                ('Correctness', models.DecimalField(decimal_places=9, max_digits=10)),
                ('GoodPinningPractice', models.DecimalField(decimal_places=9, max_digits=10)),
                ('LicenseScore', models.DecimalField(decimal_places=9, max_digits=10)),
                ('RampUp', models.DecimalField(decimal_places=9, max_digits=10)),
                ('ResponsiveMaintainer', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='packagemetadata',
            constraint=models.UniqueConstraint(fields=('Name', 'Version'), name='unique_package'),
        ),
        migrations.AddField(
            model_name='package',
            name='Data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.packagedata'),
        ),
        migrations.AddField(
            model_name='package',
            name='Metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.packagemetadata'),
        ),
    ]
