# Generated by Django 3.2.5 on 2021-11-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('Password', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
