# Generated by Django 3.2.5 on 2021-10-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='PackagePath',
        ),
        migrations.AddField(
            model_name='package',
            name='PackageFile',
            field=models.FileField(default='', upload_to='data/'),
            preserve_default=False,
        ),
    ]
