# Generated by Django 3.2.5 on 2021-10-29 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20211028_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('MetricsId', models.AutoField(primary_key=True, serialize=False)),
                ('RampUp', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='OwnerId',
            new_name='GroupId',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='OwnerName',
            new_name='GroupName',
        ),
        migrations.RemoveField(
            model_name='package',
            name='LatestUpdate',
        ),
        migrations.RemoveField(
            model_name='package',
            name='PackageDescription',
        ),
        migrations.AddField(
            model_name='package',
            name='PackageMetrics',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registry.metrics'),
            preserve_default=False,
        ),
    ]
