# Generated by Django 3.2.5 on 2021-11-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
