# Generated by Django 3.2.5 on 2021-10-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20211028_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='PackageGroup',
        ),
        migrations.RenameField(
            model_name='metrics',
            old_name='MetricsId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='PackageFile',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='PackageId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='PackageMetrics',
            new_name='Metrics',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='PackageName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='PackageVersion',
            new_name='Version',
        ),
        migrations.RenameField(
            model_name='packagegroup',
            old_name='GroupId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='packagegroup',
            old_name='GroupName',
            new_name='Name',
        ),
    ]
