# Generated by Django 3.2.5 on 2021-10-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20211028_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Metrics',
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
    ]
