# Generated by Django 3.2.10 on 2021-12-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_packagedata_only_one_content_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packagedata',
            name='only_one_content_type',
        ),
        migrations.AlterField(
            model_name='packagerating',
            name='BusFactor',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='packagerating',
            name='Correctness',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='packagerating',
            name='GoodPinningPractice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='packagerating',
            name='LicenseScore',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='packagerating',
            name='RampUp',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='packagerating',
            name='ResponsiveMaintainer',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
