# Generated by Django 3.2.5 on 2021-10-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20211028_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='File',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Version',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='packagegroup',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='packagegroup',
            old_name='Name',
            new_name='name',
        ),
    ]
