# Generated by Django 3.2.5 on 2021-10-31 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20211028_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('URL', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PackageMetadata',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackageQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusFactor', models.DecimalField(decimal_places=9, max_digits=10)),
                ('Correctness', models.DecimalField(decimal_places=9, max_digits=10)),
                ('GoodPinningPractice', models.DecimalField(decimal_places=9, max_digits=10)),
                ('LicenseScore', models.DecimalField(decimal_places=9, max_digits=10)),
                ('RampUp', models.DecimalField(decimal_places=9, max_digits=10)),
                ('ResponsiveMaintainer', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='file',
        ),
        migrations.RemoveField(
            model_name='package',
            name='group',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='version',
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='PackageGroup',
        ),
        migrations.AddField(
            model_name='package',
            name='data',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registry.packagedata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='metadata',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registry.packagemetadata'),
            preserve_default=False,
        ),
    ]
