# Generated by Django 3.2.5 on 2021-11-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20211031_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemetadata',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
