# Generated by Django 3.2.5 on 2021-11-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_alter_packagemetadata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedata',
            name='Content',
            field=models.TextField(unique=True),
        ),
    ]
