# Generated by Django 3.2.5 on 2021-11-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_packagedata_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedata',
            name='Content',
            field=models.TextField(),
        ),
    ]
