# Generated by Django 3.2.5 on 2021-11-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_alter_packagedata_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemetadata',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='packagemetadata',
            constraint=models.UniqueConstraint(fields=('Name', 'Version'), name='unique_package'),
        ),
    ]
