# Generated by Django 3.2.5 on 2021-11-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_packagedata_registry_packagedata_content_or_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packagedata',
            name='registry_packagedata_Content_or_URL',
        ),
    ]
