# Generated by Django 3.2.5 on 2021-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_packagedata_registry_packagedata_content_or_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packagedata',
            name='registry_packagedata_content_or_url',
        ),
        migrations.AddConstraint(
            model_name='packagedata',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('Content__exact', ''), ('URL__iregex', '(\\w|\\W)+')), models.Q(('Content__iregex', '(\\w|\\W)+'), ('URL__exact', '')), _connector='OR'), name='registry_packagedata_content_or_url'),
        ),
    ]
