# Generated by Django 3.2.5 on 2021-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_auto_20211108_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemetadata',
            name='ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
