# Generated by Django 3.2.5 on 2021-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_alter_packagemetadata_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packagedata',
            name='registry_packagedata_content_or_url',
        ),
        migrations.AddConstraint(
            model_name='packagedata',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('Content__isnull', True), ('URL__isnull', False)), models.Q(('Content__isnull', False), ('URL__isnull', True)), _connector='OR'), name='registry_packagedata_content_or_url'),
        ),
    ]
