# This is a basic workflow to help you get started with Actions

name: CD for Google App Engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: package_registry/app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
      
#       - name: Newman Action
#         uses: matt-ball/newman-action@v1.0.2



        # Install the newman command line utility and also install the html extra reporter
#       - name: Install newman
#         run: |
#           npm install -g newman
#           npm install -g newman-reporter-htmlextra


#       # Make directory to upload the test results
#       - name: Make Directory for results
#         run: mkdir -p testResults


#       # Run the POSTMAN collection
#       - name: Run POSTMAN collection
#         run: |
#           newman run PRODUCTION.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html


#       # Upload the contents of Test Results directory to workspace
#       - name: Output the run Details
#         uses: actions/upload-artifact@v2
#         with:
#           name: RunReports
#           path: testResults
