# This is a basic workflow to help you get started with Actions

name: CD for Google App Engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      PROD_DATABASE_PASSWORD: ${{ secrets.PROD_DATABASE_PASSWORD }} 
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CHECK ENV VARS
        run: python -c 'import os; print(os.environ)'

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        
        with:
          deliverables: package_registry/app.yaml   
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
        
      - name: Postman Test Suite
        uses: matt-ball/newman-action@master
        with:
            collection: PRODUCTION.postman_collection.json
            environment: Tests.postman_environment.json
      

