name: Newman Run

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Newman Action
        # You may pin to the exact commit or the version.
        # uses: matt-ball/newman-action@573e42a0a75f676336800aa40d7b63b2acdc4ff3
        uses: matt-ball/newman-action@v1.0.2
        with:
          # Postman API key
#           apiKey: # optional
          # Collection to use
          collection: PRODUCTION.postman_collection.json
          # Environment to use
